name: Build for Linux

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Linux 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build the executable with PyInstaller
        run: |
          pyinstaller --onefile --add-data "assets:assets" reset_machine_id.py

      - name: Upload Linux build artifact
        uses: actions/upload-artifact@v3
        with:
          name: cursor-vip-linux
          path: dist/reset_machine_id  # 上传 Linux 可执行文件
